defaults:
  - cluster: v100
  - calculator: uma
  - _self_

benchmark_name: ligand_strain

job:
  run_name: ${checkpoint.model_name}
  run_dir: ${cluster.run_dir}
  device_type: ${cluster.device}
  debug: ${cluster.debug}
  scheduler:
    mode: ${cluster.mode}
    distributed_init_method: FILE
    num_array_jobs: 100
    slurm:
      partition: ${cluster.partition}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: omol-leaderboard
    group: ${checkpoint.model_name}
    job_type: ${benchmark_name}

runner:
  _target_: fairchem.core.components.calculate.omol_runner.OMolRunner
  calculator: ${calculator}
  input_data: ${cluster.data_root_dir}/ligand_strain_inputs.pkl
  benchmark_name: ${benchmark_name}
  benchmark:
    _target_: fairchem.core.components.calculate.single.recipes.omol.ligand_strain
    _partial_: True

reducer:
  _target_: fairchem.core.components.benchmark.omol_reducer.OMolReducer
  benchmark_name: ${benchmark_name}
  benchmark_labels: ${cluster.data_root_dir}/ligand_strain_targets.json
  evaluator:
    _target_: fairchem.data.omol.modules.evaluator.ligand_strain
    _partial_: True
