defaults:
  - cluster: fair_cluster
  - backbone: H512L10
  - dataset: fair_cluster_spice
  - element_refs: spice_lin_refs
  - tasks: spice_grad
  - _self_

job:
  device_type: ${cluster.device}
  scheduler:
    mode: ${cluster.mode}
    ranks_per_node: ${cluster.ranks_per_node}
    num_nodes: 32
    slurm:
      mem_gb: ${cluster.mem_gb}
      timeout_hr: ${cluster.timeout_hr}
      cpus_per_task: ${cluster.cpus_per_task}
      additional_parameters: ${cluster.additional_parameters}
  debug: ${cluster.debug}
  run_dir: ${cluster.run_dir}
  run_name: escaip_spice_E10F20_grad_L
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: ericqu
    project: spice_v2

# cpu_graph: True
fp16: False
max_neighbors: 30
max_neighbors_pad_size: 45
cutoff_radius: 6
epochs: 300
steps: null # 80B atoms, 128 ranks, max atoms 350 (mean atoms 300)
max_atoms: 250
# normalizer_rmsd: 1.423
direct_forces_coef: 20
spice_energy_coef: 10
use_pbc: False

regress_stress: False
direct_forces: False

spice_forces_key: spice_forces

# dataset_list: ["omol"]

exclude_keys: [
  "id", # only oc20,oc22 have this
  "fid", # only oc20,oc22 have this
  "absolute_idx", # only ani has this
  "target_pos", # only ani has this
  "ref_energy", # only ani/geom have this
  "pbc", # only ani/transition1x have this
  "nads", # oc22
  "oc22", # oc22
  "formation_energy", # spice
  "total_charge", # spice
]

train_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    # omc: ${dataset.omc_train}
    # omol: ${dataset.omol_train}
    # odac: ${dataset.odac_train}
    # omat: ${dataset.omat_train}
    spice: ${dataset.spice_train}
  combined_dataset_config:
    sampling:
      type: explicit
      ratios:
        # omol.train: 4.0
        spice.train: 1.0
        # omc.train: 2.0
        # odac.train: 1.0
        # omat.train: 2.0

val_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    # omc: ${dataset.omc_val}
    # omol: ${dataset.omol_val}
    # odac: ${dataset.odac_val}
    # omat: ${dataset.omat_val}
    spice: ${dataset.spice_val}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

train_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${train_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: True
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${val_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: False
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

heads:
  energyandforcehead:
    module: fairchem.core.models.uma.escn_moe.DatasetSpecificSingleHeadWrapper
    head_cls: fairchem.core.models.escaip.EScAIP.EScAIPGradientEnergyForceStressHead
    head_kwargs:
      wrap_property: False
    dataset_names:
      - spice

runner:
  _target_: fairchem.core.components.train.train_runner.TrainEvalRunner
  train_dataloader: ${train_dataloader}
  eval_dataloader: ${eval_dataloader}
  train_eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPTrainEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    model:
      _target_: fairchem.core.models.base.HydraModel
      pass_through_head_outputs: True
      backbone: ${backbone}
      heads: ${heads}
    optimizer_fn:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: 4e-4
      weight_decay: 1e-3
    cosine_lr_scheduler_fn:
      _target_: fairchem.core.units.mlip_unit.mlip_unit._get_consine_lr_scheduler
      _partial_: true
      warmup_factor: 0.2
      warmup_epochs: 2
      lr_min_factor: 0.01
      epochs: ${epochs}
      steps: ${steps}
    print_every: 10
    clip_grad_norm: 0.1
    fp16: ${fp16}
  max_epochs: ${epochs}
  max_steps: ${steps}
  evaluate_every_n_steps: 5000
  callbacks:
    - _target_: fairchem.core.common.profiler_utils.ProfilerCallback
      job_config: ${job}
    - _target_: fairchem.core.components.train.train_runner.TrainCheckpointCallback
      checkpoint_every_n_steps: 2000
      max_saved_checkpoints: 5
