version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  labels:
    - "no-op"
    - "dependencies"
  commit-message:
    # Prefix all commit messages with "gh-actions: "
    prefix: "gh-actions"
  assignees:
    - "rayg1234"
    - "misko"
    - "mshuaibii"
    - "lbluque"

# Python dependencies
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  commit-message:
    # Prefix all commit messages with "pip: "
    prefix: "pip"
  assignees:
    - "rayg1234"
    - "misko"
    - "mshuaibii"
    - "lbluque"

# to ignore certain dependencies
#ignore:
#  - dependency-name: pymatgen
#    versions:
#      -
