include-paths:
  - src/fairchem/data/omol
  - packages/fairchem-data-omol
tag-prefix: fairchem_data_omol
tag-template: 'fairchem_data_omol-$RESOLVED_VERSION'
name-template: 'fairchem_data_omol-$RESOLVED_VERSION'
exclude-contributors: [github-actions]
categories:
  - title: New Features / Enhancements
    labels: [enhancement]
  - title: Bug Fixes
    labels: [bug]
  - title: Documentation
    labels: [documentation]
  - title: Tests
    labels: [test]
  - title: Deprecations
    labels: [deprecation]
  - title: Dependencies
    labels: [dependencies]
  - title: Other Changes
    labels: ["*"]
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What’s Changed

  $CHANGES
