data_root_dir: /checkpoint/ocp/shared/fm_training
run_dir: /checkpoint/ocp/shared/puma
account: ocp
qos: ocp
mode: SLURM
device: CUDA
ranks_per_node: 8
dataloader_workers: 8
debug: False
mem_gb: 1000
