"""
Auto-generated Triton kernel for l=4 Wigner D computation.

Generated by wigner_d_triton_codegen.py
- Degree: 8
- Monomials: 165
- Outputs: 81 (9x9)
"""

import torch
import triton
import triton.language as tl


@triton.jit(do_not_specialize=['N', 'stride_q', 'stride_d', 'stride_c_row'])
def _wigner_d_l4_kernel(
    q_ptr,              # Input: (N, 4)
    D_ptr,              # Output: (N, 81)
    C_T_ptr,            # Coefficients transposed: (165, 81)
    N,                  # Number of quaternions
    stride_q,           # Stride for q
    stride_d,           # Stride for D
    stride_c_row,       # Stride for C_T rows
    BLOCK_Q: tl.constexpr,
):
    """Fused Wigner D l=4 kernel with 165 monomials."""
    pid = tl.program_id(0)

    q_start = pid * BLOCK_Q
    q_offsets = q_start + tl.arange(0, BLOCK_Q)
    q_mask = q_offsets < N

    # Load quaternion components
    w = tl.load(q_ptr + q_offsets * stride_q + 0, mask=q_mask, other=0.0)
    x = tl.load(q_ptr + q_offsets * stride_q + 1, mask=q_mask, other=0.0)
    y = tl.load(q_ptr + q_offsets * stride_q + 2, mask=q_mask, other=0.0)
    z = tl.load(q_ptr + q_offsets * stride_q + 3, mask=q_mask, other=0.0)

    # Precompute powers
    # Powers of w
    w2 = w * w
    w3 = w2 * w
    w4 = w2 * w2
    w5 = w4 * w
    w6 = w3 * w3
    w7 = w4 * w3
    w8 = w4 * w4

    # Powers of x
    x2 = x * x
    x3 = x2 * x
    x4 = x2 * x2
    x5 = x4 * x
    x6 = x3 * x3
    x7 = x4 * x3
    x8 = x4 * x4

    # Powers of y
    y2 = y * y
    y3 = y2 * y
    y4 = y2 * y2
    y5 = y4 * y
    y6 = y3 * y3
    y7 = y4 * y3
    y8 = y4 * y4

    # Powers of z
    z2 = z * z
    z3 = z2 * z
    z4 = z2 * z2
    z5 = z4 * z
    z6 = z3 * z3
    z7 = z4 * z3
    z8 = z4 * z4

    # Compute each output element
    for out_idx in tl.static_range(81):
        acc = tl.zeros((BLOCK_Q,), dtype=w.dtype)
        c_base = out_idx

        # a=0 monomials
        acc += tl.load(C_T_ptr + 0 * stride_c_row + c_base) * (z8)
        acc += tl.load(C_T_ptr + 1 * stride_c_row + c_base) * (y * z7)
        acc += tl.load(C_T_ptr + 2 * stride_c_row + c_base) * (y2 * z6)
        acc += tl.load(C_T_ptr + 3 * stride_c_row + c_base) * (y3 * z5)
        acc += tl.load(C_T_ptr + 4 * stride_c_row + c_base) * (y4 * z4)
        acc += tl.load(C_T_ptr + 5 * stride_c_row + c_base) * (y5 * z3)
        acc += tl.load(C_T_ptr + 6 * stride_c_row + c_base) * (y6 * z2)
        acc += tl.load(C_T_ptr + 7 * stride_c_row + c_base) * (y7 * z)
        acc += tl.load(C_T_ptr + 8 * stride_c_row + c_base) * (y8)
        acc += tl.load(C_T_ptr + 9 * stride_c_row + c_base) * (x * z7)
        acc += tl.load(C_T_ptr + 10 * stride_c_row + c_base) * (x * y * z6)
        acc += tl.load(C_T_ptr + 11 * stride_c_row + c_base) * (x * y2 * z5)
        acc += tl.load(C_T_ptr + 12 * stride_c_row + c_base) * (x * y3 * z4)
        acc += tl.load(C_T_ptr + 13 * stride_c_row + c_base) * (x * y4 * z3)
        acc += tl.load(C_T_ptr + 14 * stride_c_row + c_base) * (x * y5 * z2)
        acc += tl.load(C_T_ptr + 15 * stride_c_row + c_base) * (x * y6 * z)
        acc += tl.load(C_T_ptr + 16 * stride_c_row + c_base) * (x * y7)
        acc += tl.load(C_T_ptr + 17 * stride_c_row + c_base) * (x2 * z6)
        acc += tl.load(C_T_ptr + 18 * stride_c_row + c_base) * (x2 * y * z5)
        acc += tl.load(C_T_ptr + 19 * stride_c_row + c_base) * (x2 * y2 * z4)
        acc += tl.load(C_T_ptr + 20 * stride_c_row + c_base) * (x2 * y3 * z3)
        acc += tl.load(C_T_ptr + 21 * stride_c_row + c_base) * (x2 * y4 * z2)
        acc += tl.load(C_T_ptr + 22 * stride_c_row + c_base) * (x2 * y5 * z)
        acc += tl.load(C_T_ptr + 23 * stride_c_row + c_base) * (x2 * y6)
        acc += tl.load(C_T_ptr + 24 * stride_c_row + c_base) * (x3 * z5)
        acc += tl.load(C_T_ptr + 25 * stride_c_row + c_base) * (x3 * y * z4)
        acc += tl.load(C_T_ptr + 26 * stride_c_row + c_base) * (x3 * y2 * z3)
        acc += tl.load(C_T_ptr + 27 * stride_c_row + c_base) * (x3 * y3 * z2)
        acc += tl.load(C_T_ptr + 28 * stride_c_row + c_base) * (x3 * y4 * z)
        acc += tl.load(C_T_ptr + 29 * stride_c_row + c_base) * (x3 * y5)
        acc += tl.load(C_T_ptr + 30 * stride_c_row + c_base) * (x4 * z4)
        acc += tl.load(C_T_ptr + 31 * stride_c_row + c_base) * (x4 * y * z3)
        acc += tl.load(C_T_ptr + 32 * stride_c_row + c_base) * (x4 * y2 * z2)
        acc += tl.load(C_T_ptr + 33 * stride_c_row + c_base) * (x4 * y3 * z)
        acc += tl.load(C_T_ptr + 34 * stride_c_row + c_base) * (x4 * y4)
        acc += tl.load(C_T_ptr + 35 * stride_c_row + c_base) * (x5 * z3)
        acc += tl.load(C_T_ptr + 36 * stride_c_row + c_base) * (x5 * y * z2)
        acc += tl.load(C_T_ptr + 37 * stride_c_row + c_base) * (x5 * y2 * z)
        acc += tl.load(C_T_ptr + 38 * stride_c_row + c_base) * (x5 * y3)
        acc += tl.load(C_T_ptr + 39 * stride_c_row + c_base) * (x6 * z2)
        acc += tl.load(C_T_ptr + 40 * stride_c_row + c_base) * (x6 * y * z)
        acc += tl.load(C_T_ptr + 41 * stride_c_row + c_base) * (x6 * y2)
        acc += tl.load(C_T_ptr + 42 * stride_c_row + c_base) * (x7 * z)
        acc += tl.load(C_T_ptr + 43 * stride_c_row + c_base) * (x7 * y)
        acc += tl.load(C_T_ptr + 44 * stride_c_row + c_base) * (x8)

        # a=1 monomials
        acc += tl.load(C_T_ptr + 45 * stride_c_row + c_base) * (w * z7)
        acc += tl.load(C_T_ptr + 46 * stride_c_row + c_base) * (w * y * z6)
        acc += tl.load(C_T_ptr + 47 * stride_c_row + c_base) * (w * y2 * z5)
        acc += tl.load(C_T_ptr + 48 * stride_c_row + c_base) * (w * y3 * z4)
        acc += tl.load(C_T_ptr + 49 * stride_c_row + c_base) * (w * y4 * z3)
        acc += tl.load(C_T_ptr + 50 * stride_c_row + c_base) * (w * y5 * z2)
        acc += tl.load(C_T_ptr + 51 * stride_c_row + c_base) * (w * y6 * z)
        acc += tl.load(C_T_ptr + 52 * stride_c_row + c_base) * (w * y7)
        acc += tl.load(C_T_ptr + 53 * stride_c_row + c_base) * (w * x * z6)
        acc += tl.load(C_T_ptr + 54 * stride_c_row + c_base) * (w * x * y * z5)
        acc += tl.load(C_T_ptr + 55 * stride_c_row + c_base) * (w * x * y2 * z4)
        acc += tl.load(C_T_ptr + 56 * stride_c_row + c_base) * (w * x * y3 * z3)
        acc += tl.load(C_T_ptr + 57 * stride_c_row + c_base) * (w * x * y4 * z2)
        acc += tl.load(C_T_ptr + 58 * stride_c_row + c_base) * (w * x * y5 * z)
        acc += tl.load(C_T_ptr + 59 * stride_c_row + c_base) * (w * x * y6)
        acc += tl.load(C_T_ptr + 60 * stride_c_row + c_base) * (w * x2 * z5)
        acc += tl.load(C_T_ptr + 61 * stride_c_row + c_base) * (w * x2 * y * z4)
        acc += tl.load(C_T_ptr + 62 * stride_c_row + c_base) * (w * x2 * y2 * z3)
        acc += tl.load(C_T_ptr + 63 * stride_c_row + c_base) * (w * x2 * y3 * z2)
        acc += tl.load(C_T_ptr + 64 * stride_c_row + c_base) * (w * x2 * y4 * z)
        acc += tl.load(C_T_ptr + 65 * stride_c_row + c_base) * (w * x2 * y5)
        acc += tl.load(C_T_ptr + 66 * stride_c_row + c_base) * (w * x3 * z4)
        acc += tl.load(C_T_ptr + 67 * stride_c_row + c_base) * (w * x3 * y * z3)
        acc += tl.load(C_T_ptr + 68 * stride_c_row + c_base) * (w * x3 * y2 * z2)
        acc += tl.load(C_T_ptr + 69 * stride_c_row + c_base) * (w * x3 * y3 * z)
        acc += tl.load(C_T_ptr + 70 * stride_c_row + c_base) * (w * x3 * y4)
        acc += tl.load(C_T_ptr + 71 * stride_c_row + c_base) * (w * x4 * z3)
        acc += tl.load(C_T_ptr + 72 * stride_c_row + c_base) * (w * x4 * y * z2)
        acc += tl.load(C_T_ptr + 73 * stride_c_row + c_base) * (w * x4 * y2 * z)
        acc += tl.load(C_T_ptr + 74 * stride_c_row + c_base) * (w * x4 * y3)
        acc += tl.load(C_T_ptr + 75 * stride_c_row + c_base) * (w * x5 * z2)
        acc += tl.load(C_T_ptr + 76 * stride_c_row + c_base) * (w * x5 * y * z)
        acc += tl.load(C_T_ptr + 77 * stride_c_row + c_base) * (w * x5 * y2)
        acc += tl.load(C_T_ptr + 78 * stride_c_row + c_base) * (w * x6 * z)
        acc += tl.load(C_T_ptr + 79 * stride_c_row + c_base) * (w * x6 * y)
        acc += tl.load(C_T_ptr + 80 * stride_c_row + c_base) * (w * x7)

        # a=2 monomials
        acc += tl.load(C_T_ptr + 81 * stride_c_row + c_base) * (w2 * z6)
        acc += tl.load(C_T_ptr + 82 * stride_c_row + c_base) * (w2 * y * z5)
        acc += tl.load(C_T_ptr + 83 * stride_c_row + c_base) * (w2 * y2 * z4)
        acc += tl.load(C_T_ptr + 84 * stride_c_row + c_base) * (w2 * y3 * z3)
        acc += tl.load(C_T_ptr + 85 * stride_c_row + c_base) * (w2 * y4 * z2)
        acc += tl.load(C_T_ptr + 86 * stride_c_row + c_base) * (w2 * y5 * z)
        acc += tl.load(C_T_ptr + 87 * stride_c_row + c_base) * (w2 * y6)
        acc += tl.load(C_T_ptr + 88 * stride_c_row + c_base) * (w2 * x * z5)
        acc += tl.load(C_T_ptr + 89 * stride_c_row + c_base) * (w2 * x * y * z4)
        acc += tl.load(C_T_ptr + 90 * stride_c_row + c_base) * (w2 * x * y2 * z3)
        acc += tl.load(C_T_ptr + 91 * stride_c_row + c_base) * (w2 * x * y3 * z2)
        acc += tl.load(C_T_ptr + 92 * stride_c_row + c_base) * (w2 * x * y4 * z)
        acc += tl.load(C_T_ptr + 93 * stride_c_row + c_base) * (w2 * x * y5)
        acc += tl.load(C_T_ptr + 94 * stride_c_row + c_base) * (w2 * x2 * z4)
        acc += tl.load(C_T_ptr + 95 * stride_c_row + c_base) * (w2 * x2 * y * z3)
        acc += tl.load(C_T_ptr + 96 * stride_c_row + c_base) * (w2 * x2 * y2 * z2)
        acc += tl.load(C_T_ptr + 97 * stride_c_row + c_base) * (w2 * x2 * y3 * z)
        acc += tl.load(C_T_ptr + 98 * stride_c_row + c_base) * (w2 * x2 * y4)
        acc += tl.load(C_T_ptr + 99 * stride_c_row + c_base) * (w2 * x3 * z3)
        acc += tl.load(C_T_ptr + 100 * stride_c_row + c_base) * (w2 * x3 * y * z2)
        acc += tl.load(C_T_ptr + 101 * stride_c_row + c_base) * (w2 * x3 * y2 * z)
        acc += tl.load(C_T_ptr + 102 * stride_c_row + c_base) * (w2 * x3 * y3)
        acc += tl.load(C_T_ptr + 103 * stride_c_row + c_base) * (w2 * x4 * z2)
        acc += tl.load(C_T_ptr + 104 * stride_c_row + c_base) * (w2 * x4 * y * z)
        acc += tl.load(C_T_ptr + 105 * stride_c_row + c_base) * (w2 * x4 * y2)
        acc += tl.load(C_T_ptr + 106 * stride_c_row + c_base) * (w2 * x5 * z)
        acc += tl.load(C_T_ptr + 107 * stride_c_row + c_base) * (w2 * x5 * y)
        acc += tl.load(C_T_ptr + 108 * stride_c_row + c_base) * (w2 * x6)

        # a=3 monomials
        acc += tl.load(C_T_ptr + 109 * stride_c_row + c_base) * (w3 * z5)
        acc += tl.load(C_T_ptr + 110 * stride_c_row + c_base) * (w3 * y * z4)
        acc += tl.load(C_T_ptr + 111 * stride_c_row + c_base) * (w3 * y2 * z3)
        acc += tl.load(C_T_ptr + 112 * stride_c_row + c_base) * (w3 * y3 * z2)
        acc += tl.load(C_T_ptr + 113 * stride_c_row + c_base) * (w3 * y4 * z)
        acc += tl.load(C_T_ptr + 114 * stride_c_row + c_base) * (w3 * y5)
        acc += tl.load(C_T_ptr + 115 * stride_c_row + c_base) * (w3 * x * z4)
        acc += tl.load(C_T_ptr + 116 * stride_c_row + c_base) * (w3 * x * y * z3)
        acc += tl.load(C_T_ptr + 117 * stride_c_row + c_base) * (w3 * x * y2 * z2)
        acc += tl.load(C_T_ptr + 118 * stride_c_row + c_base) * (w3 * x * y3 * z)
        acc += tl.load(C_T_ptr + 119 * stride_c_row + c_base) * (w3 * x * y4)
        acc += tl.load(C_T_ptr + 120 * stride_c_row + c_base) * (w3 * x2 * z3)
        acc += tl.load(C_T_ptr + 121 * stride_c_row + c_base) * (w3 * x2 * y * z2)
        acc += tl.load(C_T_ptr + 122 * stride_c_row + c_base) * (w3 * x2 * y2 * z)
        acc += tl.load(C_T_ptr + 123 * stride_c_row + c_base) * (w3 * x2 * y3)
        acc += tl.load(C_T_ptr + 124 * stride_c_row + c_base) * (w3 * x3 * z2)
        acc += tl.load(C_T_ptr + 125 * stride_c_row + c_base) * (w3 * x3 * y * z)
        acc += tl.load(C_T_ptr + 126 * stride_c_row + c_base) * (w3 * x3 * y2)
        acc += tl.load(C_T_ptr + 127 * stride_c_row + c_base) * (w3 * x4 * z)
        acc += tl.load(C_T_ptr + 128 * stride_c_row + c_base) * (w3 * x4 * y)
        acc += tl.load(C_T_ptr + 129 * stride_c_row + c_base) * (w3 * x5)

        # a=4 monomials
        acc += tl.load(C_T_ptr + 130 * stride_c_row + c_base) * (w4 * z4)
        acc += tl.load(C_T_ptr + 131 * stride_c_row + c_base) * (w4 * y * z3)
        acc += tl.load(C_T_ptr + 132 * stride_c_row + c_base) * (w4 * y2 * z2)
        acc += tl.load(C_T_ptr + 133 * stride_c_row + c_base) * (w4 * y3 * z)
        acc += tl.load(C_T_ptr + 134 * stride_c_row + c_base) * (w4 * y4)
        acc += tl.load(C_T_ptr + 135 * stride_c_row + c_base) * (w4 * x * z3)
        acc += tl.load(C_T_ptr + 136 * stride_c_row + c_base) * (w4 * x * y * z2)
        acc += tl.load(C_T_ptr + 137 * stride_c_row + c_base) * (w4 * x * y2 * z)
        acc += tl.load(C_T_ptr + 138 * stride_c_row + c_base) * (w4 * x * y3)
        acc += tl.load(C_T_ptr + 139 * stride_c_row + c_base) * (w4 * x2 * z2)
        acc += tl.load(C_T_ptr + 140 * stride_c_row + c_base) * (w4 * x2 * y * z)
        acc += tl.load(C_T_ptr + 141 * stride_c_row + c_base) * (w4 * x2 * y2)
        acc += tl.load(C_T_ptr + 142 * stride_c_row + c_base) * (w4 * x3 * z)
        acc += tl.load(C_T_ptr + 143 * stride_c_row + c_base) * (w4 * x3 * y)
        acc += tl.load(C_T_ptr + 144 * stride_c_row + c_base) * (w4 * x4)

        # a=5 monomials
        acc += tl.load(C_T_ptr + 145 * stride_c_row + c_base) * (w5 * z3)
        acc += tl.load(C_T_ptr + 146 * stride_c_row + c_base) * (w5 * y * z2)
        acc += tl.load(C_T_ptr + 147 * stride_c_row + c_base) * (w5 * y2 * z)
        acc += tl.load(C_T_ptr + 148 * stride_c_row + c_base) * (w5 * y3)
        acc += tl.load(C_T_ptr + 149 * stride_c_row + c_base) * (w5 * x * z2)
        acc += tl.load(C_T_ptr + 150 * stride_c_row + c_base) * (w5 * x * y * z)
        acc += tl.load(C_T_ptr + 151 * stride_c_row + c_base) * (w5 * x * y2)
        acc += tl.load(C_T_ptr + 152 * stride_c_row + c_base) * (w5 * x2 * z)
        acc += tl.load(C_T_ptr + 153 * stride_c_row + c_base) * (w5 * x2 * y)
        acc += tl.load(C_T_ptr + 154 * stride_c_row + c_base) * (w5 * x3)

        # a=6 monomials
        acc += tl.load(C_T_ptr + 155 * stride_c_row + c_base) * (w6 * z2)
        acc += tl.load(C_T_ptr + 156 * stride_c_row + c_base) * (w6 * y * z)
        acc += tl.load(C_T_ptr + 157 * stride_c_row + c_base) * (w6 * y2)
        acc += tl.load(C_T_ptr + 158 * stride_c_row + c_base) * (w6 * x * z)
        acc += tl.load(C_T_ptr + 159 * stride_c_row + c_base) * (w6 * x * y)
        acc += tl.load(C_T_ptr + 160 * stride_c_row + c_base) * (w6 * x2)

        # a=7 monomials
        acc += tl.load(C_T_ptr + 161 * stride_c_row + c_base) * (w7 * z)
        acc += tl.load(C_T_ptr + 162 * stride_c_row + c_base) * (w7 * y)
        acc += tl.load(C_T_ptr + 163 * stride_c_row + c_base) * (w7 * x)

        # a=8 monomials
        acc += tl.load(C_T_ptr + 164 * stride_c_row + c_base) * (w8)

        # Store result
        tl.store(D_ptr + q_offsets * stride_d + out_idx, acc, mask=q_mask)


def quaternion_to_wigner_d_l4_triton(q: torch.Tensor) -> torch.Tensor:
    """
    Compute l=4 Wigner D matrix using fused Triton kernel.

    Args:
        q: Unit quaternions of shape (N, 4) in (w, x, y, z) convention.

    Returns:
        Wigner D matrices of shape (N, 9, 9).
    """
    from fairchem.core.models.uma.common.wigner_d_triton_utils import _get_kernel_data

    N = q.shape[0]
    D_flat = torch.empty(N, 81, dtype=q.dtype, device=q.device)

    C_T = _get_kernel_data(4, q.dtype, q.device)

    BLOCK_Q = 64
    grid = ((N + BLOCK_Q - 1) // BLOCK_Q,)

    _wigner_d_l4_kernel[grid](
        q, D_flat, C_T, N,
        stride_q=q.stride(0),
        stride_d=D_flat.stride(0),
        stride_c_row=C_T.stride(0),
        BLOCK_Q=BLOCK_Q,
    )

    return D_flat.view(N, 9, 9)

