snapshot_dir: fm_training/dataset_sync_250225
omol_preview_snapshot_dir: ${dataset.snapshot_dir}/omol/250303
omol_final_snapshot_dir: omol/250409-final

osc:
  splits:
    test:
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/test/
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: osc_energy
    forces: ${osc_forces_key}
    stress: osc_stress
  transforms:
    common_transform:
      dataset_name: osc
    stress_reshape_transform:
      dataset_name: osc

omol_preview:
  splits:
    test:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
    test_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - organometallics
    test_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    test_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    test_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
            - spice
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

omol_final:
  splits:
    test:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/test
    test_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - metal_complexes
    test_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    test_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    test_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
            - spice
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

# odac: 

omat:
  splits:
    test_wbm:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-relax
    test_ecombo:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-relax
    test_rcomp:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-relax
    test_hea:
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_hea
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omat_energy
    forces: ${omat_forces_key}
    stress: omat_stress
  transforms:
    common_transform:
      dataset_name: omat
    stress_reshape_transform:
      dataset_name: omat

# oc20:  # no energies in dataset
#   splits:
#     test_id:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/id
#     test_ood_ads:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/ood_ads
#     test_ood_both:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/ood_both
#     test_ood_cat:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/ood_cat
#   format: ase_db
#   a2g_args:
#     r_energy: True
#     r_forces: True
#     r_edges: ${cpu_graph}
#     radius: ${cutoff_radius}
#     max_neigh: ${max_neighbors}
#   key_mapping:
#     energy: oc20_energy
#     forces: ${oc20_forces_key}
#   transforms:
#     common_transform:
#       dataset_name: oc20
