snapshot_dir: fm_training/dataset_sync_250225
omol_preview_snapshot_dir: ${dataset.snapshot_dir}/omol/250303
omol_snapshot_dir: omol/250430-release/launch/

omol_preview:
  splits:
    val:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
    val_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - organometallics
    val_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    val_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    val_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
    metal_ligand_ood:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/metal_ligand_ood
    test:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
    test_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - organometallics
    test_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    test_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    test_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

omol:  # omol final 250430-release
  splits:
    val:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/val
    val_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - metal_complexes
    val_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    val_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    val_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
    metal_ligand_ood:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/metal_ligand_ood
    test:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/test
    test_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - metal_complexes
    test_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    test_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    test_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_snapshot_dir}/test
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

omc:
  splits:
    test:
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/test/
    val:
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/val/
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omc_energy
    forces: ${omc_forces_key}
    stress: omc_stress
  transforms:
    common_transform:
      dataset_name: omc
    stress_reshape_transform:
      dataset_name: omc

odac:
  splits:
    val:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/odac/250225/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: odac_energy
    forces: ${odac_forces_key}
  transforms:
    common_transform:
      dataset_name: odac

omat:
  splits:
    val:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-relax
    test_wbm:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-relax
    test_ecombo:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_ecombo/rattled-relax
    test_rcomp:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_rcomp/rattled-relax
    test_hea:
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_hea
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omat_energy
    forces: ${omat_forces_key}
    stress: omat_stress
  transforms:
    common_transform:
      dataset_name: omat
    stress_reshape_transform:
      dataset_name: omat

oc20:
  splits:
    val_id:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/id
    val_ood_both:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/ood_both
# no energy labels in dataset
#     test_id:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/id
#     test_ood_ads:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/ood_ads
#     test_ood_both:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/ood_both
#     test_ood_cat:
#       src:
#         - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/test/ood_cat
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: oc20_energy
    forces: ${oc20_forces_key}
  transforms:
    common_transform:
      dataset_name: oc20
