snapshot_dir: fm_training/dataset_sync_250225
omol_preview_snapshot_dir: ${dataset.snapshot_dir}/omol/250303
omol_final_snapshot_dir: omol/250409-final

osc:
  splits:
    val:
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/val/
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: osc_energy
    forces: ${osc_forces_key}
    stress: osc_stress
  transforms:
    common_transform:
      dataset_name: osc
    stress_reshape_transform:
      dataset_name: osc

omol_preview:
  splits:
    val:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
    val_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - organometallics
    val_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    val_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    val_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
            - spice
    metal_ligand_ood:
      src: ${cluster.data_root_dir}/${dataset.omol_preview_snapshot_dir}/metal_ligand_ood
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

omol_final:
  splits:
    val:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
    val_metal_complexes:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - metal_complexes
    val_electrolytes:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    val_biomolecules:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    val_neutralorganics:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
            - spice
    metal_ligand_ood:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/metal_ligand_ood
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

odac:
  splits:
    val:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/odac/250225/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: odac_energy
    forces: ${odac_forces_key}
  transforms:
    common_transform:
      dataset_name: odac

omat:
  splits:
    val:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-relax
    test:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-relax
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omat_energy
    forces: ${omat_forces_key}
    stress: omat_stress
  transforms:
    common_transform:
      dataset_name: omat
    stress_reshape_transform:
      dataset_name: omat

oc20:
  splits:
    val_id:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/id
    val_ood_both:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/ood_both
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: oc20_energy
    forces: ${oc20_forces_key}
  transforms:
    common_transform:
      dataset_name: oc20
