model: fairchem.core.models.puma.escn_moe.eSCNMDMoeBackbone
moe_dropout: 0.05
moe_layer_type: pytorch
num_experts: ${num_moe_experts}
use_composition_embedding: true
use_global_embedding: false

max_num_elements: 100
sphere_channels: ${channels}
lmax: ${lmax}
mmax: ${mmax}

otf_graph: ${otf_graph}
max_neighbors: ${max_neighbors}
use_pbc: True
use_pbc_single: True

cutoff: ${cutoff_radius}
edge_channels: ${channels}
distance_function: gaussian
num_distance_basis: 64

regress_forces: True
regress_stress: ${regress_stress}
direct_forces: ${direct_forces}

num_layers: ${layers}
hidden_channels: ${channels}
norm_type: rms_norm_sh
act_type: gate
ff_type: spectral

chg_spin_emb_type: "rand_emb"
cs_emb_grad: True
dataset_list: ${dataset_list}
