job:
  run_dir: /checkpoint/jagritisahoo
  run_name: eSEN-30M-OAM
  scheduler:
    mode: SLURM
    num_array_jobs: 500
    slurm:
      partition: scavenge
      mem_gb: 256
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: test-benchmarks

benchmark_name: hea-s2ef
target_properties: ["energy", "forces"]

runner:
  _target_: fairchem.core.components.calculate.singlepoint_runner.SinglePointRunner
  calculator:
       _target_: fairchem.experimental.foundation_models.modules.calculator.MLIPCalculator
       inference_ckpt_path: /checkpoint/xiangfu/selected_ckpts/puma_sm_32MoE_conserved_0331_605000.pt
       dataset_name: omat
       energy_key: omat_energy
       forces_key: omat_forces
       stress_key: omat_stress
       act_ckpt: True
    # _target_: fairchem.core.OCPCalculator
    # checkpoint_path: /checkpoint/lbluque/model-checkpoints/esen/eSEN-30M-OMat-MPsAlex/checkpoint.pt
    # trainer: equiformerv2_forces
    #cpu: False
  input_data:
    _target_: fairchem.core.datasets.ase_datasets.AseDBDataset
    config:
      src: /large_experiments/opencatalyst/foundation_models/data/bulks/high_entropy/HEA_subsample_datasets/filtered_asedbs/bcc_subsample/bcc_subsample.aselmdb
  save_target_properties: ${target_properties}

reducer:
  _target_: fairchem.core.components.benchmark.benchmark_reducer.JsonDFReducer
  target_data_keys: ${target_properties}
  benchmark_name: ${benchmark_name}
  index_name: sid
