job:
  run_name: eSEN-30M-OAM-Phonon
  # run_name: PUMA-SM-0MoP-Phonon
  # run_name: PUMA-SM-32MoP-Phonon
  run_dir: /checkpoint/xiangfu/benchmark_test
  scheduler:
    mode: SLURM
    num_array_jobs: 500
    slurm:
      partition: scavenge
      mem_gb: 256
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: test-benchmarks

# job:
#   device_type: CPU
#   scheduler:
#     mode: LOCAL
#   logger:
#     _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
#     _partial_: true
#     entity: fairchem
#     project: test-benchmarks

benchmark_name: mdr-phonon

runner:
  _target_: fairchem.core.components.calculate.phonon_runner.MDRPhononRunner
  calculator:
    _target_: fairchem.core.OCPCalculator
    checkpoint_path: /checkpoint/xiangfu/esen_release/after_surgery/oam/checkpoint.pt
    cpu: False
  # calculator:
  #   _target_: fairchem.core.modules.calculator.MLIPCalculator
  #   inference_ckpt_path: /checkpoint/xiangfu/selected_ckpts/puma_sm_noMoE_conserved_0331_745000.pt
  #   # inference_ckpt_path: /checkpoint/xiangfu/selected_ckpts/puma_sm_32MoE_conserved_0331_605000.pt
  #   dataset_name: omat
  #   energy_key: omat_energy
  #   forces_key: omat_forces
  #   stress_key: omat_stress
  #   act_ckpt: True
  input_data:
    _target_: fairchem.core.components.calculate.phonon_runner.get_mdr_phonon_data_list
    index_df_path: /large_experiments/opencatalyst/MDsim/MDR_Phonon/pbe.json
    phonon_file_path: /large_experiments/opencatalyst/MDsim/MDR_Phonon/pbe
    debug: False
  displacement: 0.01

reducer:
  _target_: fairchem.core.components.benchmark.benchmark_reducer.JsonDFReducer
  target_data_path: /large_experiments/opencatalyst/MDsim/MDR_Phonon/pbe.json
  benchmark_name: ${benchmark_name}
  index_name: mp_id
