job:
  run_name: esen_sm_is2re
  run_dir: /checkpoint/mshuaibi/benchmark_test
  scheduler:
    mode: SLURM
    num_array_jobs: 200
    num_nodes: 1
    ranks_per_node: 1
    slurm:
      partition: scavenge
      mem_gb: 256
      timeout_hr: 72
      cpus_per_task: 8
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: test-benchmarks

runner:
  _target_: fairchem.core.components.calculate.adsorption_runner.AdsorptionRunner
  calculator:
    _target_: fairchem.core.modules.calculator.MLIPCalculator
    inference_ckpt_path: /checkpoint/xiangfu/selected_ckpts/puma_sm_32MoE_conserved_0331_605000.pt
    dataset_name: oc20
    energy_key: oc20_energy
    forces_key: oc20_forces
  save_relaxed_atoms: False
  relax_surface: True
  optimizer_cls: LBFGS
  fmax: 0.05
  steps: 300
  input_data:
    _target_: fairchem.core.datasets.ase_datasets.AseDBDataset
    config:
      src: /large_experiments/opencatalyst/foundation_models/data/catalysis/benchmark

reducer:
  _target_: fairchem.core.components.benchmark.adsorption_reducer.AdsorptionReducer
  target_data_key: target
  benchmark_name: adsorption
  index_name: sid
