#fairchem -c puma_speed.yaml +run_dir_root=/checkpoint/ocp/misko/benchmark

runner:
  _target_: fairchem.core.components.benchmark.puma_speed_benchmark.InferenceBenchRunner
  timeiters: 10
  natoms_list: [100, 1000, 10000]
  model_checkpoints: {
    # "puma_sm_cons": "/checkpoint/ocp/shared/temp/escn_md_k4L2_cons.pt",
    "puma_sm_actual": "/checkpoint/ocp/shared/puma_checkpoints/202505-0622-2445-47b9/full_run_dir/checkpoints/step_950000/inference_ckpt.pt"
    # "puma_md_cons": "/checkpoint/ocp/shared/temp/escn_md_K10L4_cons.pt"
    # "puma_lg": "/checkpoint/ocp/shared/temp/puma_lg_migrated.pt"
  }
  run_dir_root: ${run_dir_root}
  inference_settings:
    _target_: fairchem.core.units.mlip_unit.api.inference.InferenceSettings
    tf32: True
    activation_checkpointing: False
    merge_mole: True
    compile: True
    wigner_cuda: True
    external_graph_gen: True
