defaults:
  - cluster: h100
  - dataset: validate
  - element_refs: puma_hof_lin_refs
  - tasks: puma_direct
  - checkpoint: puma_031425_lg_direct
  - _self_

job:
  device_type: ${cluster.device}
  scheduler:
    mode: ${cluster.mode}
    ranks_per_node: ${cluster.ranks_per_node}
    num_nodes: 4
    slurm:
      account: ${cluster.account}
      qos: ${cluster.qos}
  debug: ${cluster.debug}
  run_dir: ${cluster.run_dir}
  run_name: ${checkpoint.model_name}
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: puma-evals

max_atoms: 700
max_neighbors: 30

cutoff_radius: 6
cpu_graph: True
normalizer_rmsd: 1.568 # v0 # 1.422 v1 
direct_forces_coef: 30
osc_energy_coef: 10
omol_energy_coef: 30
odac_energy_coef: 10
oc20_energy_coef: 10
omat_energy_coef: 10

regress_stress: False

oc20_forces_key: forces
omat_forces_key: forces
omol_forces_key: forces
odac_forces_key: forces
osc_forces_key: forces

exclude_keys: [
  "id", # only oc20,oc22 have this
  "fid", # only oc20,oc22 have this
  "absolute_idx", # only ani has this
  "target_pos", # only ani has this
  "ref_energy", # only ani/geom have this
  "pbc", # only ani/transition1x have this
  "nads", # oc22
  "oc22", # oc22
  "formation_energy", # spice
  "total_charge", # spice
]

eval_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    osc: ${dataset.osc}
    omol_preview: ${dataset.omol_preview}
    omol_final: ${dataset.omol_final}
    odac: ${dataset.odac}
    omat: ${dataset.omat}
    oc20: ${dataset.oc20}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${eval_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: False
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

runner:
  _target_: fairchem.core.components.evaluate.eval_runner.EvalRunner
  dataloader: ${eval_dataloader}
  eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    model:
      _target_: fairchem.core.units.mlip_unit.mlip_unit.load_inference_model
      checkpoint_location: ${checkpoint.ckpt_path}
      use_ema: True
