defaults:
  - cluster: h100
  - backbone: K10L4
  - dataset: wombat
  - element_refs: wombat_lin_refs
  - _self_

job:
  device_type: ${cluster.device}
  scheduler:
    mode: ${cluster.mode}
    ranks_per_node: ${cluster.ranks_per_node}
    num_nodes: 1
    slurm:
      account: ${cluster.account}
      qos: ${cluster.qos}
      mem_gb: ${cluster.mem_gb}
  debug: ${cluster.debug}
  run_dir: ${cluster.run_dir}
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: tnt_trainer

num_moe_experts: 0
max_neighbors: 300
cutoff_radius: 6.0
epochs: 2
steps: null
max_atoms: 350
bf16: False
cpu_graph: True
otf_graph: False

regress_stress: False
direct_forces: False

oc20_forces_key: oc20_forces
omat_forces_key: omat_forces
omol_forces_key: omol_forces
osc_forces_key: osc_forces

dataset_list: ["oc20", "omol", "omat","osc"]

exclude_keys: [
  "id", # only oc20,oc22 have this
  "fid", # only oc20,oc22 have this
  "absolute_idx", # only ani has this
  "target_pos", # only ani has this
  "ref_energy", # only ani/geom have this
  "pbc", # only ani/transition1x have this
  "nads", # oc22
  "oc22", # oc22
  "formation_energy", # spice
  "total_charge", # spice
]

train_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    osc: ${dataset.osc_train}
    omol: ${dataset.omol_train}
    omat: ${dataset.omat_train}
    oc20: ${dataset.oc20_train}
  combined_dataset_config: {sampling: {type: temperature, temperature: 2.0}}

val_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    osc: ${dataset.osc_val}
    omol: ${dataset.omol_val}
    omat: ${dataset.omat_val}
    oc20: ${dataset.oc20_val}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

train_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${train_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: True
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${val_dataset}
  batch_sampler_fn:
     _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
     _partial_: True
     max_atoms: ${max_atoms}
     shuffle: False
     seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

tasks:
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: osc_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    element_references:
      _target_: fairchem.core.modules.normalization.element_references.ElementReferences
      element_references:
        _target_: torch.Tensor
        _args_:
          - ${element_refs.osc_elem_refs}
    datasets:
      - osc
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: omol_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    element_references:
      _target_: fairchem.core.modules.normalization.element_references.ElementReferences
      element_references:
        # do to the scale of the numbers this needs to be a double
        _target_: torch.DoubleTensor
        _args_:
          - ${element_refs.omol_elem_refs}
    datasets:
      - omol
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: oc20_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    element_references:
      _target_: fairchem.core.modules.normalization.element_references.ElementReferences
      element_references:
        _target_: torch.Tensor
        _args_:
          - ${element_refs.oc20_elem_refs}
    datasets:
      - oc20
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: omat_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    element_references:
      _target_: fairchem.core.modules.normalization.element_references.ElementReferences
      element_references:
        _target_: torch.Tensor
        _args_:
          - ${element_refs.omat_elem_refs}
    datasets:
      - omat
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: osc_forces
    level: atom
    property: forces
    train_on_free_atoms: True
    eval_on_free_atoms: True
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.L2NormLoss
      reduction: per_structure
      coefficient: 50
    out_spec:
      dim: [3]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - osc
    metrics:
      - mae
      - cosine_similarity
      - magnitude_error
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: oc20_forces
    level: atom
    property: forces
    train_on_free_atoms: True
    eval_on_free_atoms: True
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.L2NormLoss
      reduction: per_structure
      coefficient: 50
    out_spec:
      dim: [3]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - oc20
    metrics:
      - mae
      - cosine_similarity
      - magnitude_error
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: omat_forces
    level: atom
    property: forces
    train_on_free_atoms: True
    eval_on_free_atoms: True
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.L2NormLoss
      reduction: per_structure
      coefficient: 50
    out_spec:
      dim: [3]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - omat
    metrics:
      - mae
      - cosine_similarity
      - magnitude_error
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: omol_forces
    level: atom
    property: forces
    train_on_free_atoms: True
    eval_on_free_atoms: True
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.L2NormLoss
      reduction: per_structure
      coefficient: 50
    out_spec:
      dim: [3]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - omol
    metrics:
      - mae
      - cosine_similarity
      - magnitude_error

heads:
  energyandforcehead:
    module: fairchem.core.models.puma.escn_moe.DatasetSpecificMoEWrapper
    head_cls: fairchem.core.models.puma.escn_md.MLP_EFS_Head
    head_kwargs:
      wrap_property: False
    dataset_names:
      - omol
      - omat
      - oc20
      - osc

runner:
  _target_: fairchem.core.components.train.train_runner.TrainEvalRunner
  train_dataloader: ${train_dataloader}
  eval_dataloader: ${eval_dataloader}
  train_eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPTrainEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    model:
      _target_: fairchem.core.models.base.HydraModel
      pass_through_head_outputs: True
      backbone: ${backbone}
      heads: ${heads}
    optimizer_fn:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: 8e-4
      weight_decay: 1e-3
    cosine_lr_scheduler_fn:
      _target_: fairchem.core.units.mlip_unit.mlip_unit._get_consine_lr_scheduler
      _partial_: true
      warmup_factor: 0.2
      warmup_epochs: 0.01
      lr_min_factor: 0.01
      epochs: ${epochs}
      steps: ${steps}
    print_every: 10
    clip_grad_norm: 100
    bf16: ${bf16}
  max_epochs: ${epochs}
  max_steps: ${steps}
  evaluate_every_n_steps: 5000
  callbacks:
    - _target_: fairchem.core.common.profiler_utils.ProfilerCallback
      job_config: ${job}
    - _target_: fairchem.core.components.train.train_runner.TrainCheckpointCallback
      checkpoint_every_n_steps: 1000
