[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-fancy-pypi-readme>=24"]
build-backend = "hatchling.build"

[project]
name = "fairchem-applications-fastcsp"
dynamic = ["version", "readme"]
description = "FastCSP: Accelerated Molecular Crystal Structure Prediction with Universal Model for Atoms"
license = {text = "MIT License"}
dependencies = [
    "fairchem-core",
    "pyarrow",
    "submitit",
    "swifter"
]

[project.optional-dependencies]
# These are not installed by default. The following dependencies require manual installation and cannot be installed via pip:
#   - genarris: see https://github.com/Yi5817/Genarris for installation instructions.
#   - csd-python-api: requires a valid CCDC license and see https://downloads.ccdc.cam.ac.uk/documentation/API/installation_notes.html for installation instructions.
# Do NOT expect 'pip install fairchem-applications-fastcsp[genarris]' or '[csd]' to install Genarris or CSD Python API.
genarris = []
csd = []
vasp = ["fairchem-data-omc",]

[project.scripts]
fastcsp = "fairchem.applications.fastcsp.core.cli:cli_main"

[project.urls]
repository = "http://github.com/Fair-Chem/src/fairchem/applications/fastcsp"
documentation = "https://fair-chem.github.io/"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"
git_describe_command = 'git describe --tags --match fairchem_applications_fastcsp-*'

[tool.hatch.build]
directory = "../../dist-applications-fastcsp"

[tool.hatch.build.targets.sdist]
only-include = ["src/fairchem/applications/fastcsp"]

[tool.hatch.build.targets.wheel]
sources = ["src"]
only-include = ["src/fairchem/applications/fastcsp"]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
  { path = "src/fairchem/applications/fastcsp/README.md" }
]
