data_root_dir: /fsx-ocp-med/shared/
run_dir: /fsx-checkpoints/${oc.env:USER}/
account: ocp
qos: ocp_high
mode: LOCAL
device: CUDA
ranks_per_node: 1
dataloader_workers: 0
debug: True
mem_gb: 0
cpus_per_task: 12
