run_dir: /checkpoint/ocp/rgao/correctness
scheduler:
  mode: SLURM
  num_nodes: 1
  ranks_per_node: 8
  slurm:
    account: ocp
    qos: h200_dev
    mem_gb: 0
    cpus_per_task: 24
graph_parallel_group_size: 8
