data_root_dir: /fsx-ocp-med/shared/benchmark
checkpoint_root_dir: /fsx-ocp-med/shared/uma_checkpoints
run_dir: /fsx-checkpoints/${oc.env:USER}/
account: ocp
partition: ""
qos: lowest
mode: LOCAL
device: CUDA
ranks_per_node: 1
debug: True
mem_gb: 120
