data_root_dir: /fsx-ocp-med/shared/benchmark
checkpoint_root_dir: /fsx-ocp-med/shared/uma_checkpoints
run_dir: /fsx-checkpoints/${oc.env:USER}/
account: ocp
qos: lowest
partition: ""
mode: SLURM
device: CUDA
debug: False
mem_gb: 120
