data_root_dir: /large_experiments/opencatalyst/foundation_models/data/omol/evals/benchmark_inputs/250911
checkpoint_root_dir: /large_experiments/opencatalyst/foundation_models/checkpoints/uma
run_dir: /checkpoint/${oc.env:USER}/
account: null
partition: scavenge
qos: null
mode: LOCAL
device: CUDA
debug: True
mem_gb: 256
