- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: spice_energy
  level: system
  property: energy
  loss_fn:
    _target_: fairchem.core.modules.loss.DDPMTLoss
    loss_fn:
      _target_: fairchem.core.modules.loss.PerAtomMAELoss
    coefficient: ${spice_energy_coef}
  out_spec:
    dim: [1]
    dtype: float32
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: 0.1271905523885108
    rmsd: 1.0757999822144813
  element_references:
    _target_: fairchem.core.modules.normalization.element_references.ElementReferences
    element_references:
      _target_: torch.DoubleTensor
      _args_:
        - ${element_refs.spice_elem_refs}
  datasets:
    - spice
  metrics:
    - mae
    - per_atom_mae
- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: spice_forces
  level: atom
  property: forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
  loss_fn:
    _target_: fairchem.core.modules.loss.DDPMTLoss
    loss_fn:
      _target_: fairchem.core.modules.loss.L2NormLoss
    reduction: per_structure
    coefficient: ${direct_forces_coef}
  out_spec:
    dim: [3]
    dtype: float32
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: 0.0
    rmsd: 1.0757999822144813
  datasets:
    - spice
  metrics:
    - mae
    - cosine_similarity
    - magnitude_error
