
dataset_name: odac

job:
  run_name: pairwise_ct_${dataset_name}
  run_dir: /checkpoint/ocp/shared/puma
  device_type: CPU
  debug: False
  scheduler:
    mode: SLURM
    distributed_init_method: FILE
    num_array_jobs: 200
    slurm:
      partition: learn
      qos: ocp_high
      mem_gb: 1000
      timeout_hr: 72

runner:
  _target_: fairchem.core.components.calculate.pairwise_ct_runner.PairwiseCountRunner
  dataset_cfg: /checkpoint/ocp/shared/pairwise_data/preview_config.yaml
  ds_name: ${dataset_name}
  radius: 3.5
  portion: 1