defaults:
  - cluster: h100
  - dataset: wombat
  - _self_

job:
  device_type: ${cluster.device}
  scheduler:
    mode: ${cluster.mode}
    ranks_per_node: ${cluster.ranks_per_node}
    num_nodes: 1
    slurm:
      account: ${cluster.account}
      qos: ${cluster.qos}
      mem_gb: ${cluster.mem_gb}
  debug: ${cluster.debug}
  run_dir: ${cluster.run_dir}
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: tnt_trainer

checkpoint_location: /home/lbluque/checkpoint/sandbox/inference_ckpt.pt
cpu_graph: False
max_neighbors: 20

oc20_forces_key: forces
omat_forces_key: forces
omol_forces_key: forces
osc_forces_key: forces

exclude_keys: [
  "id", # only oc20,oc22 have this
  "fid", # only oc20,oc22 have this
  "absolute_idx", # only ani has this
  "target_pos", # only ani has this
  "ref_energy", # only ani/geom have this
  "pbc", # only ani/transition1x have this
  "nads", # oc22
  "oc22", # oc22
  "formation_energy", # spice
  "total_charge", # spice
]

val_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    osc: ${dataset.osc_val}
    omol: ${dataset.omol_val}
    omat: ${dataset.omat_val}
    oc20: ${dataset.oc20_val}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${val_dataset}
  batch_sampler_fn:
#    _target_: fairchem.core.common.data_parallel.BalancedBatchSampler
#    _partial_: True
#    batch_size: 10
#    shuffle: True
#    seed: 28
     _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
     _partial_: True
     max_atoms: 350
     shuffle: False
     seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

tasks:
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: osc_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - osc
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: omol_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - omol
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: oc20_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - oc20
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: omat_energy
    level: system
    property: energy
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.PerAtomMAELoss
      coefficient: 10
    out_spec:
      dim: [1]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - omat
    metrics:
      - mae
  - _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
    name: forces
    level: atom
    property: forces
    train_on_free_atoms: True
    eval_on_free_atoms: True
    loss_fn:
      _target_: fairchem.core.modules.loss.DDPMTLoss
      loss_fn:
        _target_: fairchem.core.modules.loss.L2NormLoss
      reduction: per_structure
      coefficient: 50
    out_spec:
      dim: [3]
      dtype: float32
    normalizer:
      _target_: fairchem.core.modules.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: 2.783857161157615
    datasets:
      - osc
      - omol
      - oc20
      - omat
    metrics:
      - mae
      - cosine_similarity
      - magnitude_error

runner:
  _target_: fairchem.experimental.foundation_models.components.evaluate.eval_runner.EvalRunner
  dataloader: ${eval_dataloader}
  eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    model:
      _target_: fairchem.core.units.mlip_unit.mlip_unit.load_inference_model
      checkpoint_location: ${checkpoint_location}
