name: Release Drafter - fairchem_lammps

on:
  push:
    branches:
      - main
    paths:
      - 'src/fairchem/lammps/**'
      - 'packages/fairchem-lammps/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
        # write permission is required to create a github release
        contents: write
        pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
          latest: true
          config-name: release-drafter-lammps.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
