name: tests_lammps

on:
  workflow_call:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches: [main]

jobs:
  test_gpu_conda:
    runs-on: 4-core-ubuntu-gpu-t4
    permissions:
      contents: read
      # Needed to manually set commit status
      statuses: write
    strategy:
      max-parallel: 10
      matrix:
        python_version: ['3.12']

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          generate-run-shell: true # This is the default behavior
          environment-name: test_env # Specifies a new environment to be created
          create-args: python=3.12 # Specifies packages to install into the new environment

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.HEAD_SHA }}
          # Optional: get full history if needed
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/multi-trigger-setup
        with:
          status-context: '${{ github.job }} (${{ matrix.python_version }})'

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python_version }}

      - name: Install core dependencies and package
        run: |
          micromamba install lammps
          python -m pip install --upgrade pip
          pip install packages/fairchem-core[dev,extras]
          pip install packages/fairchem-lammps
          pip install -r tests/requirements.txt # pin test packages

      - name: Core GPU tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          NCCL_DEBUG=INFO pytest tests/lammps --durations=0 -vv -m gpu
      - name: Cleanup
        if: always()
        uses: ./.github/actions/multi-trigger-cleanup
        with:
          status-context: '${{ github.job }} (${{ matrix.python_version }})'
