name: tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows:
      - "contributor check"
    types:
      - completed

jobs:
  test:
    runs-on: 32-core-ubuntu
    permissions:
      contents: read
      # Needed by set-commit-status-action
      statuses: write
    strategy:
      max-parallel: 10
      matrix:
        python_version: ['3.10', '3.12']

    steps:
      # If triggered by a workflow_run on a PR, the status won't show up by
      # default on the PR checks so we need to do it manually. This sets the
      # status to pending, but more importantly it adds a URL to the PR check
      # linking to this workflow job.
      - name: Report initial status after workflow_run trigger
        if: ${{ github.event_name == 'workflow_run' }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending
      
      # If this was triggered by a completed workflow run, we want to make
      # sure that workflow actually succeeded. If it didn't, we should skip
      # the remainder of the tests.
      - name: Fail on triggering workflow failure
        if: ${{
            github.event_name == 'workflow_run'
            && github.event.workflow_run.conclusion != 'success'
          }}
        run: |
          echo "Skipping tests because the triggering workflow did not succeed"
          exit 1
      
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # The path to the sha of the commit we want to test will depend
          # on the trigger type. If a workflow_run trigger, then we want
          # the sha from the head of the branch that triggered it. For 
          # pushes and manual triggers, we want the sha of the branch.
          ref: |
            ${{
              github.event.workflow_run.head_sha ||
              github.event.pull_request.head.sha ||
              github.sha
            }}
          # Optional: get full history if needed
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python_version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install core dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install packages/fairchem-core[dev]
          pip install packages/fairchem-data-oc[dev]
          pip install packages/fairchem-demo-ocpapi[dev]
          pip install -r tests/requirements.txt # pin test packages

      - name: Install additional dependencies
        run: |
          wget https://github.com/m3g/packmol/archive/refs/tags/v20.15.0.tar.gz
          tar -xzvf v20.15.0.tar.gz
          cd packmol-20.15.0
          ./configure
          make
          echo "$(readlink -f .)" >> $GITHUB_PATH

      - name: Test core with pytest
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest tests --durations=0 -vv --ignore=tests/demo/ocpapi/tests/integration/ --ignore=tests/applications/ --cov-report=xml --cov=fairchem -c ./packages/fairchem-core/pyproject.toml

      - name: Core GPU tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest tests/core --durations=0 -vv -m gpu -c ./packages/fairchem-core/pyproject.toml -s

      - if: ${{ matrix.python_version == '3.12' }}
        name: codecov-report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false # optional (default = false)
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
      
      # Manually report the final status if this was triggered by a
      # workflow_run since it won't show up by default on the checks
      # of the triggering PR
      - name: Report final status after workflow_run trigger
        if: ${{
            always()
            && github.event_name == 'workflow_run'
          }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}

  test_gpu:
    runs-on: 4-core-ubuntu-gpu-t4
    permissions:
      contents: read
      # Needed by set-commit-status-action
      statuses: write
    strategy:
      max-parallel: 10
      matrix:
        python_version: ['3.12']

    steps:
      # If triggered by a workflow_run on a PR, the status won't show up by
      # default on the PR checks so we need to do it manually. This sets the
      # status to pending, but more importantly it adds a URL to the PR check
      # linking to this workflow job.
      - name: Report initial status after workflow_run trigger
        if: ${{ github.event_name == 'workflow_run' }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending
      
      # If this was triggered by a completed workflow run, we want to make
      # sure that workflow actually succeeded. If it didn't, we should skip
      # the remainder of the tests.
      - name: Fail on triggering workflow failure
        if: ${{
            github.event_name == 'workflow_run'
            && github.event.workflow_run.conclusion != 'success'
          }}
        run: |
          echo "Skipping tests because the triggering workflow did not succeed"
          exit 1
      
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # The path to the sha of the commit we want to test will depend
          # on the trigger type. If a workflow_run trigger, then we want
          # the sha from the head of the branch that triggered it. For 
          # pushes and manual triggers, we want the sha of the branch.
          ref: |
            ${{
              github.event.workflow_run.head_sha ||
              github.event.pull_request.head.sha ||
              github.sha
            }}
          # Optional: get full history if needed
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python_version }}

      - name: Install core dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install packages/fairchem-core[dev]
          pip install -r tests/requirements.txt # pin test packages

      - name: Core GPU tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest tests/core --durations=0 -vv -m gpu -c ./packages/fairchem-core/pyproject.toml
      
      # Manually report the final status if this was triggered by a
      # workflow_run since it won't show up by default on the checks
      # of the triggering PR
      - name: Report final status after workflow_run trigger
        if: ${{
            always()
            && github.event_name == 'workflow_run'
          }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
