snapshot_dir: fm_training/dataset_sync_250225
omol_final_snapshot_dir: omol/250409-final

osc_train:
  splits:
    train:
      sample_n: 10000
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/val/
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    r_stress: ${regress_stress}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: osc_energy
    forces: ${osc_forces_key}
    stress: osc_stress
  transforms:
    common_transform:
      dataset_name: osc
    stress_reshape_transform:
      dataset_name: osc

osc_val:
  splits:
    val:
      sample_n: 10
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/val/
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    r_stress: ${regress_stress}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: osc_energy
    forces: ${osc_forces_key}
    stress: osc_stress
  transforms:
    common_transform:
      dataset_name: osc
    stress_reshape_transform:
      dataset_name: osc

omol_train:
  splits:
    train:
      sample_n: 10000
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

omol_val:
  splits:
    pdb_ood:
      sample_n: 10
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

odac_train:
  splits:
    train:
      sample_n: 10000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/odac/250225/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: odac_energy
    forces: ${odac_forces_key}
  transforms:
    common_transform:
      dataset_name: odac

odac_val:
  splits:
    val:
      sample_n: 10
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/odac/250225/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: odac_energy
    forces: ${odac_forces_key}
  transforms:
    common_transform:
      dataset_name: odac

omat_train:
  splits:
    train:
      sample_n: 10000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/aimd-from-PBE-1000-npt
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    r_stress: ${regress_stress}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: omat_energy
    forces: ${omat_forces_key}
    stress: omat_stress
  transforms:
    common_transform:
      dataset_name: omat
    stress_reshape_transform:
      dataset_name: omat

omat_val:
  splits:
    val:
      sample_n: 10
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-1000-npt
    test:
      sample_n: 10
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-npt
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    r_stress: ${regress_stress}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: omat_energy
    forces: ${omat_forces_key}
    stress: omat_stress
  transforms:
    common_transform:
      dataset_name: omat
    stress_reshape_transform:
      dataset_name: omat

oc20_train:
  splits:
    train:
      sample_n: 10000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/id
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: oc20_energy
    forces: ${oc20_forces_key}
  transforms:
    common_transform:
      dataset_name: oc20

oc20_val:
  splits:
    val_id:
      sample_n: 10
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/id
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    max_neigh: ${max_neighbors}
    radius: ${cutoff_radius}
  key_mapping:
    energy: oc20_energy
    forces: ${oc20_forces_key}
  transforms:
    common_transform:
      dataset_name: oc20
